# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  PRODUCTION_SSH_ENDPOINT: placeholder
  PRODUCTION_SERVER_PRIVATE_KEY: placeholder
  PRODUCTION_SSH_USER: placeholder
  PRODUCTION_SSH_TARGET_FOLDER: placeholder

pool:
  name: Default
  # This is required for Microsoft-hosted Pipeline agents
  #vmImage: ubuntu-latest

steps:

- bash: echo production_ssh_endpoint $(PRODUCTION_SSH_ENDPOINT)
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: $(PRODUCTION_SSH_ENDPOINT)
    sourceFolder: 'target/'
    contents: 'herborder.jar'
    targetFolder: $(PRODUCTION_TARGET_FOLDER)
    readyTimeout: '20000'
    overwrite: true
    failOnEmptySource: true

- task: SSH@0
  inputs:
    sshEndpoint: $(PRODUCTION_SSH_ENDPOINT)
    runOptions: 'commands'
    commands: 'sudo systemctl restart herborder.service'
    readyTimeout: '20000'
