# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  production_ssh_endpoint: placeholder
  production_server_private_key: placeholder
  production_ssh_user: placeholder
  production_ssh_target_folder: placeholder

pool:
  name: Default
  # This is required for Microsoft-hosted Pipeline agents
  #vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: $PRODUCTION_SSH_ENDPOINT
    sourceFolder: 'target/'
    contents: 'herborder.jar'
    targetFolder: $PRODUCTION_TARGET_FOLDER
    readyTimeout: '20000'
    overwrite: true
    failOnEmptySource: true

- task: SSH@0
  inputs:
    sshEndpoint: $PRODUCTION_SSH_ENDPOINT
    runOptions: 'commands'
    commands: 'sudo systemctl restart herborder.service'
    readyTimeout: '20000'
